version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.9 # You can choose an image that fits your project
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - 'MD5:c9:b3:9d:9b:2d:ac:a7:77:ef:5a:28:ce:eb:d0:e1:52'
      - run:
          name: Update Server Hyro
          command: ssh ubuntu@13.39.157.132 -o StrictHostKeyChecking=no "cd /home/ubuntu/hyro-monorepo && git fetch && git pull && source ~/.nvm/nvm.sh && nvm use 16 && npm install && chown -R www-data:www-data ."

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development
