export const brandsType =  {
    ami_paris: "ami_paris",
    amiri: "amiri",
    balenciaga: "balenciaga",
    burberry: "burberry",
    celine: "celine",
    chanel: "chanel",
    chrome_hearts: "chrome_hearts",
    courreges: "courreges",
    designer: "designer",
    dior: "dior",
    fendi: "fendi",
    givenchy: "givenchy",
    gucci: "gucci",
    jewelry: "jewelry",
    lanvin: "lanvin",
    louis_vuitton: "louis_vuitton",
    marni: "marni",
    moncler: "moncler",
    nike_jordan: "nike_jordan",
    off_white: "off_white",
    other: "other",
    palm_angels: "palm_angels",
    prada: "prada",
    versace: "versace",
    yves_saint_laurent: 'yves_saint_laurent',
    gallery_dept: "gallery_dept"
}
